### ISSUE TITLE
Fields with same name

### ISSUE THREAD

**Issue by aadlung** [madnh/FPDM#2]
Hi,

I love this library, nevertheless I have the issue that I often have large PDF forms where e.g. "name" or "street" or "city" are fields with the same name, used many times in the same PDF file.
So the user filling out the form manually only needs to enter it once.
Could it be that this library does not support that? If I have multiple fields with the same name, I get the Exception 
```
FPDF-Merge Error: field street not found
````
in
fpdm.php:2088 Stack trace: #0 fpdm.php(863): FPDM\FPDM->Error('field street no...') #1 fpdm.php(471): FPDM\FPDM->set_field_value('current', 'street', 'Mystreet 1234') #2

Cheers,
Andy

**Comment by aadlung** [comment]
In addition, it seems that only text fields are supported, no checkboxes for example?

**Comment by madnh** [comment]
Hi @aadlung , sorry for slow reply!
This respository is just a wrapper of http://www.fpdf.org/en/script/script93.php, so I can't support about issues :(

Thank you for using of this respository :)

**Comment by dev-aikalmine** [comment]
will you able to solve this issue
